### ISSUE TITLE
error when signing in

### ISSUE THREAD

**Issue by ghost** [frannyfx/freezer#9]
"HandshakeException:
Handshake error in client (OS Error:

CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:359))"

this is definitely the worst app in the world and you still keep developing it, DELETE IT

![Screenshot_20220120-213050](https://user-images.githubusercontent.com/94427652/150457521-b59dccd5-de7f-4b5d-8cae-6328f58d707c.png)

**Comment by frannyfx** [comment]
That is not my app you silly man
